### ISSUE TITLE
Abandoned repo and gem?

### ISSUE THREAD

**Issue by brenes** [robertjwhitney/programr#6]
Hi,

I have solved some of the issues pointed out in other issues and I'm planning to do some updating job including some features I'd wish there were in the gem like being able to export and import the environment of the robot.

My question is Is this repo still maintained? If I submit some PR will they be merged? And will a new version of the gem be published?

If the maintainer has no time (I'd understand it) Is there anyway I could handle it? Or should I create a new gem?

Thanks!

**Comment by robertjwhitney** [comment]
Send a PR

**Comment by boykoc** [comment]
Hi @robertjwhitney, in line with this post, are there reasons why you haven't accepted the other PRs?
